### PR TITLE
Suppress resolving addresses for 1st stage bootloader output

### LINKED ISSUE #977: espflash fails to resolve some bootloader addresses
Sometimes we get: 

```
INFO ] Flashing has completed!
Commands:
    CTRL+R    Reset chip
    CTRL+C    Exit

ESP-ROM:esp32c6-20220919
Build:Sep 19 2022
rst:0x1 (POWERON),boot:0xc (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:2
load:0x40875730,len:0x175c
0x40875730 - g_shared_buffers
    at ??:??
load:0x4086b910,len:0xec8
0x4086b910 - g_shared_buffers
    at ??:??
load:0x4086e610,len:0x31c4
0x4086e610 - g_shared_buffers
    at ??:??
entry 0x4086b91a
0x4086b91a - g_shared_buffers
    at ??:??
I (23) boot: ESP-IDF v5.5.1-838-gd66ebb86d2e 2nd stage bootloader
I (24) boot: compile time Nov 27 2025 09:46:10
``` 
This has been present in `espflash` for a long time, @bjoernQ suggested we may want to suppress the address resolving on this scenario.

### PR DESCRIPTION
**Pull request by bjoernQ**
Closes #977

Just in case this also adds an option to fall back to the previous behavior but in general I'd say this should help to not scare new users and reduce noise for seasoned users

### CODE REVIEW

File: espflash/src/flasher/mod.rs [hunk 1]
```diff
@@ -463,8 +463,8 @@ impl DeviceInfo {
     pub fn rom(&self) -> Option<Vec<u8>> {
         match self.chip {
             Chip::Esp32 => {
-                if let Some((major, _)) = self.revision {
-                    if major >= 3 {
+                if let Some((_, minor)) = self.revision {
```
Comment (bjoernQ) [inline espflash/src/flasher/mod.rs:466]: these changes are needed after fixing the efuse reading (in a previous PR) - I just noticed it when working on this

File: espflash/src/cli/monitor/mod.rs [hunk 2]
```diff
@@ -107,9 +107,13 @@ pub fn monitor(
     let firmware_elf = elfs.first().map(|v| &**v);
     let stdout = stdout();
     let mut stdout = if monitor_args.no_addresses {
+        if monitor_args.all_addresses {
+            log::warn!("Suppressing address resolution with `--all-addresses` given");
```
Comment (SergioGasquez) [inline espflash/src/cli/monitor/mod.rs]:
```suggestion
            log::warn!("Using ` --no-addresses` disables address resolution, making `--all-addresses` ineffective. Consider using only one of these flags."
```

**Review by SergioGasquez — APPROVED** [review]
LGTM! Only one minor nitpick comment! Also, I found out that format was weird: 

```
espflash on  suppress-rom-bootloader-address-resolving [$] via 🦀 v1.93.0-nightly took 3s 
❯ cargo r -r --bin espflash flash espflash/tests/data/esp32c3 --monitor --all-addresses --no-addresses
...
 [2025-11-28T11:50:18Z INFO ] Flashing has completed!
Commands:
    CTRL+R    Reset chip
    CTRL+C    Exit

[2025-11-28T11:50:18Z WARN ] Suppressing address resolution with `--all-addresses` given
                                                                                        ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x40380862
SPIWP:0xee
mode:DIO, clock div:2
load:0x3fcd5820,len:0x15c4
load:0x403cbf10,len:0xc84
load:0x403ce710,len:0x2fd0
entry 0x403cbf1a
```

See the `ESP-ROM:esp32c3-api1-20210207`
