### PR TITLE
bugfix: Don't use canonicalized strings on Windows

### LINKED ISSUE #209: "The parameter is incorrect" error when flashing from windows
Hi, 

I'm new to rust and embedded in general but I believe there is a regression in espflash 1.6.0 when running from windows. 

```plain
espflash COM3 .\target\xtensa-esp32-espidf\debug\test
Error: ←[31mespflash::serial_error←[0m

  ←[31mx←[0m Error while connecting to device
←[31m  |-> ←[0mIO error while using serial port: The parameter is incorrect. (os error 87)
←[31m  `-> ←[0mThe parameter is incorrect. (os error 87)
```

Running the same command on 1.5.1 is successful. My environment is Windows 10 (build 19044). Happy to provide any additional details if required.

### PR DESCRIPTION
**Pull request by JurajSadel**
closes #209

### CODE REVIEW

**Comment by MabezDev** [comment]
Just passing by, I don't understand the full issue, but could it be the `to_string_lossy` that's the real issue? `find_serial_port` should _probably_ take a PathBuf?

**Comment by MabezDev** [comment]
> Just passing by, I don't understand the full issue, but could it be the `to_string_lossy` that's the real issue? `find_serial_port` should _probably_ take a PathBuf, not a String?

We looked into this, it seems canonicalize doesn't work with "dummy" device paths like `COM4` for example, hence this error. Therefore this change is correct.

File: espflash/src/cli/serial.rs [hunk 1]
```diff
@@ -22,9 +22,13 @@ pub fn get_serial_port_info(
     let ports = detect_usb_serial_ports().unwrap_or_default();
 
     if let Some(serial) = &matches.serial {
```
Comment (jessebraham) [inline espflash/src/cli/serial.rs:24]: Would you mind adding a comment explaining this please? There are a couple things going on here and it isn't immediately clear to others what the motivation for this is:

- The call to `canonicalize()` was originally added to resolve #177
- This then causes issues on Windows, so we need to handle Windows/Posix differently

**Review by jessebraham — APPROVED** [review]
